---
- name: mysql 8.0 installed
  ansible.builtin.apt:
    name: mysql-server={{u22_mysql_version}}
    state: present
- name: mysql service enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
